#!/usr/bin/env bash
# cm_covenant_114_162_propagation.sh — CM-COVENANT-114-162-PROPAGATION gate (anchor §11.4.162).
#
# ── Purpose ──────────────────────────────────────────────────────────────────
# §11.4.227(B) anchor-block integrity for §11.4.162: the anchor's BLOCK (its
# own governance paragraph, not merely the bare literal `11.4.162`) MUST be
# present EXACTLY ONCE in every owned governance context-carrier
# (CLAUDE.md / AGENTS.md / QWEN.md / GEMINI.md) across the consumer fleet
# (§11.4.157 lockstep, §11.4.35 inheritance), and every such block MUST be
# BYTE-IDENTICAL across the carriers that carry it. Block-STARTS are counted
# (line-anchored), never bare literals — a mid-body citation is a CARRIER
# (§11.4.201(7)(a)); a genuine §11.4.35 pointer-inheritance consumer carrying
# zero blocks is an honest SKIP, never a MISSING (§11.4.201(1)).
#
# ── Thin-wrapper rationale (§11.4.251) ───────────────────────────────────────
# Every gate in this family runs the IDENTICAL check and differs only in its
# gate NAME and anchor NUMBER. Keeping one full copy of the ~400-line check per
# gate would be exactly the near-identical fork §11.4.251 forbids, so the code
# lives ONCE in `lib/covenant_propagation_engine.sh` and the role values live
# in the data pack `covenant_propagation_anchors.tsv`. This file carries only
# its own gate name — required because the §11.4.227(A) ledger's structural
# instrument needs a real executable `.sh` gate site naming the gate. It is
# generated by `covenant_propagation_wrappers_generate.sh` (§11.4.77); edit
# the engine or the data pack, never this file by hand.
#
# ── Usage ────────────────────────────────────────────────────────────────────
#   cm_covenant_114_162_propagation.sh [--root <consumer-root>] [--quiet]
#     --root <dir>   consumer fleet root to scan (default: $CONSUMER_ROOT or "..")
#     --quiet        suppress per-file PASS lines (FAIL lines always shown)
#     -h|--help      print this header
#
# ── Side-effects ─────────────────────────────────────────────────────────────
#   None (read-only; no network, no commit, no device mutation).
#
# ── Dependencies ─────────────────────────────────────────────────────────────
#   bash, lib/covenant_propagation_engine.sh, lib/pointer_carrier.sh,
#   covenant_propagation_anchors.tsv. Parses clean under bash -n.
#
# ── Cross-references ─────────────────────────────────────────────────────────
#   §11.4.162 (the anchor enforced), §11.4.227(A)/(B), §11.4.201(1)/(7)(a)/(7)(b),
#   §11.4.157, §11.4.35, §11.4.251, §11.4.28/§11.4.177, §1.1 (paired mutation:
#   cm_covenant_114_162_propagation_mutation_test.sh).
#
# ── Exit codes ───────────────────────────────────────────────────────────────
#   0 PASS · 1 MISSING/DUPLICATED/DIVERGENT · 2 environment error / BLIND.
#
# Classification: universal (§11.4.17) — no project-specific data.

set -euo pipefail

GATE="CM-COVENANT-114-162-PROPAGATION"

_engine="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/lib/covenant_propagation_engine.sh"
if [ ! -r "$_engine" ]; then
    echo "${GATE}: shared propagation engine not found at $_engine" >&2
    exit 2
fi
# shellcheck source=lib/covenant_propagation_engine.sh
. "$_engine"

covenant_propagation_main "$GATE" "$@"
