#!/usr/bin/env bash
# cm_covenant_114_276_propagation_mutation_test.sh — §1.1 paired-mutation meta-test for CM-COVENANT-114-276-PROPAGATION
# (anchor §11.4.276).
#
# ── Purpose ──────────────────────────────────────────────────────────────────
# Proves CM-COVENANT-114-276-PROPAGATION is a GENUINE gate, not a bluff: it MUST
# FAIL on every planted defect class and MUST PASS on every clean / honestly
# exempt fixture (the §1.1 discriminator). Fixtures are built in a THROWAWAY
# mktemp corpus — the real repository is never mutated.
#   FAIL-expected : MISSING (mid-body citation only) · DUPLICATED (F7 class) ·
#                   DIVERGENT-HEAD · DIVERGENT-BODY · FENCE-MISSING
#   PASS-expected : POINTER-OK (genuine §11.4.35 pointer carrier) ·
#                   CLEAN (untouched corpus — the §11.4.201(1) false-positive
#                   guard) · ANCHOR-BOUNDARY (prefix-sharing decoy anchor)
#
# ── Thin-wrapper rationale (§11.4.251) ───────────────────────────────────────
# The harness is identical for every anchor, so it lives ONCE in
# `lib/covenant_propagation_mutation_engine.sh`; this file carries only its
# gate name. Generated by `covenant_propagation_wrappers_generate.sh`
# (§11.4.77) — edit the engine or the data pack, never this file by hand.
#
# ── Usage ────────────────────────────────────────────────────────────────────
#   cm_covenant_114_276_propagation_mutation_test.sh
#
# ── Side-effects ─────────────────────────────────────────────────────────────
#   Creates + removes a temp fixture dir under $TMPDIR (trap-cleaned).
#
# ── Dependencies ─────────────────────────────────────────────────────────────
#   bash, lib/covenant_propagation_mutation_engine.sh, the sibling gate script.
#   Parses clean under bash -n.
#
# ── Cross-references ─────────────────────────────────────────────────────────
#   §1.1, §11.4.276, §11.4.227(B), §11.4.201(1)/(7)(a), §11.4.157, §11.4.35,
#   §11.4.251, §11.4.107(10).
#
# ── Exit codes ───────────────────────────────────────────────────────────────
#   0 — §1.1 proof holds · 1 — a fixture was misclassified · 2 — env error.
#
# Classification: universal (§11.4.17).

set -uo pipefail

GATE="CM-COVENANT-114-276-PROPAGATION"

_mut_engine="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)/lib/covenant_propagation_mutation_engine.sh"
if [ ! -r "$_mut_engine" ]; then
    echo "META: shared mutation engine not found at $_mut_engine" >&2
    exit 2
fi
# shellcheck source=lib/covenant_propagation_mutation_engine.sh
. "$_mut_engine"

covenant_propagation_mutation_main "$GATE"
exit $?
