#!/usr/bin/env python3
"""gen_lumenignore.py - generate a root .lumenignore from an allow-list scope.

Purpose: Lumen (semantic code search) walks the WHOLE tree with filepath.WalkDir
  and only honours .gitignore / .lumenignore / .gitattributes, a hard-coded
  skip-dir set and an extension list. A project that wants Lumen to index only
  its first-party code must therefore DENY everything else. This tool turns an
  allow-list ("these roots are first-party") into an explicit, anchored deny
  list by listing the real children of every ancestor of every allowed root.
Usage: gen_lumenignore.py --repo <root> --scope <scope.json> [--out <file>]
Inputs: scope.json = {"allow": [rel dirs], "deny": [gitignore patterns applied
  inside allowed roots], "root_files": bool (keep files directly at repo root)}
Outputs: .lumenignore text (stdout or --out). Deterministic: sorted, no
  timestamps; header carries the sha256 of the scope file.
Side-effects: none besides writing --out.
Never emits a catch-all pattern ("*", "**", "/*") - Lumen refuses such roots.
Project-agnostic: every project literal lives in the consumer's scope file.
"""
import argparse
import hashlib
import json
import os
import sys


def build(repo, scope):
    allow = sorted({a.strip("/") for a in scope.get("allow", []) if a.strip("/")})
    if not allow:
        raise SystemExit("scope.allow is empty - refusing to emit a deny-everything file")
    keep = set()  # every ancestor path (relative) that leads to an allowed root
    for a in allow:
        parts = a.split("/")
        for i in range(1, len(parts) + 1):
            keep.add("/".join(parts[:i]))
    allowed = set(allow)
    lines = []
    # walk only the ancestor chain: root level, then each kept-but-not-allowed dir
    frontier = [""]
    while frontier:
        rel = frontier.pop()
        abs_dir = os.path.join(repo, rel) if rel else repo
        try:
            entries = sorted(os.listdir(abs_dir))
        except OSError:
            continue
        for name in entries:
            child = f"{rel}/{name}" if rel else name
            full = os.path.join(repo, child)
            is_dir = os.path.isdir(full) and not os.path.islink(full)
            if child in allowed:
                continue
            if child in keep and is_dir:
                frontier.append(child)
                continue
            if not is_dir:
                if rel == "" and scope.get("root_files", True):
                    continue
                if rel != "" and rel not in allowed:
                    lines.append(f"/{child}")
                continue
            lines.append(f"/{child}/")
    for pat in sorted(set(scope.get("deny", []))):
        p = pat.strip()
        if p in ("*", "**", "**/*", "/*", "/**"):
            raise SystemExit(f"catch-all deny pattern refused: {p}")
        lines.append(p if p.startswith(("/", "**")) else "/" + p)
    return sorted(set(lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--repo", required=True)
    ap.add_argument("--scope", required=True)
    ap.add_argument("--out")
    a = ap.parse_args()
    raw = open(a.scope, "rb").read()
    scope = json.loads(raw)
    body = build(os.path.abspath(a.repo), scope)
    text = (
        "# GENERATED by gen_lumenignore.py - do not edit; regenerate from the scope file.\n"
        f"# scope-sha256: {hashlib.sha256(raw).hexdigest()}\n"
        f"# allow: {', '.join(sorted(scope['allow']))}\n"
        + "\n".join(body) + "\n"
    )
    if a.out:
        with open(a.out, "w") as f:
            f.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
