#!/bin/bash
# T143 RED test (SpecKit-004 "fast-dev-cycles", User Story 6, plan task T-F03,
# contract host-resource-attribution.md HR-004/HR-003) for
# `host/host_report.py cleanup`.
#
# Fixtures (contract's own RED-fixture table, host-resource-attribution.md):
#   hr_bad_delete_no_backup       -- no --backup-marker at all: refused, untouched
#   hr_bad_backup_hash_mismatch   -- marker's recorded content address wrong: refused
#   hr_bad_no_confirmation        -- no --confirmation: refused
#   hr_bad_live_session_dir       -- target held by a live pid (real /proc cwd): refused
#   hr_good_confirmed_backed_up   -- real backup, real confirmation, --apply:
#                                     executes; the backup itself re-verifies afterwards
#   Paired mutation (this file also proves the SHAPE the mutation must catch,
#     T146 exercises the flip itself): skipping HR-004(a) re-verification would
#     let hr_bad_backup_hash_mismatch execute -- this test's mismatch fixture
#     is therefore written to be a REAL, non-trivial hash mismatch (a
#     genuinely different backup on disk, not merely a wrong string), so a
#     GREEN implementation cannot pass by accident.
#
# Producer != Verifier: every fixture backup/marker/confirmation file below is
# built by this test script directly (its own content-address function,
# reimplemented independently rather than imported from the tool under test,
# §11.4.245 derived oracle) -- never generated by calling `cleanup` itself.

set -u
HERE=$(cd "$(dirname "$0")" && pwd)
FC_ROOT=$(cd "$HERE/.." && pwd)
TOOL="$FC_ROOT/host/host_report.py"
FAIL=0; PASS=0
ok()  { PASS=$((PASS+1)); echo "PASS: $1"; }
bad() { FAIL=$((FAIL+1)); echo "FAIL: $1"; }

if [ ! -f "$TOOL" ]; then
  echo "RED: host_report.py absent at $TOOL"
  bad "host_report.py exists"
  echo "SUMMARY pass=$PASS fail=$FAIL"; exit 1
fi

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

sha256_file() { python3 -c "import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "$1"; }

mk_target() {  # mk_target <dir> <content>
  mkdir -p "$1"
  printf '%s' "$2" > "$1/marker.txt"
}

# --- hr_bad_delete_no_backup ---
T1="$WORK/t1"; mk_target "$T1" "content-one"
OUT="$WORK/out1.json"
python3 "$TOOL" cleanup --target "$T1" --backup-marker "$WORK/nope-marker.json" \
  --confirmation "$WORK/nope-confirm.json" --out "$OUT" --apply >"$WORK/o1.log" 2>&1
rc=$?
if [ "$rc" -eq 1 ] && [ -f "$T1/marker.txt" ] && [ "$(cat "$T1/marker.txt")" = "content-one" ]; then
  ok "hr_bad_delete_no_backup: refused (exit 1), target byte-identical"
else
  bad "hr_bad_delete_no_backup: expected refused+untouched, got rc=$rc target-present=$([ -f "$T1/marker.txt" ] && echo yes || echo no)"
fi

# --- hr_bad_delete_no_backup, ISOLATED: confirmation is CORRECT and present;
#     ONLY the backup marker is missing. This isolates HR-004(a) from
#     HR-004(b) (T146 finding: the combined-missing fixture above does not
#     by itself prove the marker-check is load-bearing, since disabling it
#     alone still leaves the confirmation-check refusing -- a mutation that
#     drops JUST the marker check silently passed the combined fixture).
T1B="$WORK/t1b"; mk_target "$T1B" "content-one-b"
CONFIRM1B="$WORK/confirm1b.json"
cat > "$CONFIRM1B" <<JSON
{"target": "$T1B", "operator": "test", "confirmed_at": "2026-09-30T00:00:00Z"}
JSON
python3 "$TOOL" cleanup --target "$T1B" --backup-marker "$WORK/nope-marker-1b.json" \
  --confirmation "$CONFIRM1B" --out "$WORK/out1b.json" --apply >"$WORK/o1b.log" 2>&1
rc=$?
if [ "$rc" -eq 1 ] && [ -f "$T1B/marker.txt" ]; then
  ok "hr_bad_delete_no_backup (isolated, confirmation present+correct): refused (exit 1), target untouched"
else
  bad "hr_bad_delete_no_backup (isolated): expected refused, got rc=$rc target-present=$([ -f "$T1B/marker.txt" ] && echo yes || echo no)"
fi

# --- hr_bad_backup_hash_mismatch: real backup exists, marker records the WRONG hash ---
T2="$WORK/t2"; mk_target "$T2" "content-two"
B2="$WORK/backup2"; mk_target "$B2" "DIFFERENT-content-entirely"
WRONG_HASH=$(sha256_file "$B2/marker.txt")
MARKER2="$WORK/marker2.json"
cat > "$MARKER2" <<JSON
{"target": "$T2", "backup_path": "$B2", "content_address": "$(printf '0%.0s' $(seq 1 64))"}
JSON
CONFIRM2="$WORK/confirm2.json"
cat > "$CONFIRM2" <<JSON
{"target": "$T2", "operator": "test", "confirmed_at": "2026-09-30T00:00:00Z"}
JSON
python3 "$TOOL" cleanup --target "$T2" --backup-marker "$MARKER2" --confirmation "$CONFIRM2" \
  --out "$WORK/out2.json" --apply >"$WORK/o2.log" 2>&1
rc=$?
if [ "$rc" -eq 1 ] && [ -f "$T2/marker.txt" ]; then
  ok "hr_bad_backup_hash_mismatch: refused (exit 1), target untouched"
else
  bad "hr_bad_backup_hash_mismatch: expected refused, got rc=$rc target-present=$([ -f "$T2/marker.txt" ] && echo yes || echo no)"
fi

# --- hr_bad_no_confirmation: real backup + correct marker hash, no confirmation ---
T3="$WORK/t3"; mk_target "$T3" "content-three"
B3="$WORK/backup3"; cp -a "$T3" "$B3"
python3 - "$B3" > "$WORK/addr3.txt" <<'PYEOF'
import hashlib, os, sys
root = sys.argv[1]
entries = []
for dirpath, _dirs, files in os.walk(root):
    for f in sorted(files):
        p = os.path.join(dirpath, f)
        rel = os.path.relpath(p, root)
        h = hashlib.sha256(open(p, "rb").read()).hexdigest()
        entries.append((rel, h))
entries.sort()
manifest = "\n".join("%s\0%s" % e for e in entries)
print(hashlib.sha256(manifest.encode()).hexdigest())
PYEOF
ADDR3=$(cat "$WORK/addr3.txt")
MARKER3="$WORK/marker3.json"
cat > "$MARKER3" <<JSON
{"target": "$T3", "backup_path": "$B3", "content_address": "$ADDR3"}
JSON
python3 "$TOOL" cleanup --target "$T3" --backup-marker "$MARKER3" --confirmation "$WORK/nope-confirm3.json" \
  --out "$WORK/out3.json" --apply >"$WORK/o3.log" 2>&1
rc=$?
if [ "$rc" -eq 1 ] && [ -f "$T3/marker.txt" ]; then
  ok "hr_bad_no_confirmation: refused (exit 1), target untouched"
else
  bad "hr_bad_no_confirmation: expected refused, got rc=$rc target-present=$([ -f "$T3/marker.txt" ] && echo yes || echo no)"
fi

# --- hr_bad_live_session_dir: real backup + marker + confirmation, but a live
#     process has this target as its cwd -- must be refused regardless.
T4="$WORK/t4"; mk_target "$T4" "content-four"
B4="$WORK/backup4"; cp -a "$T4" "$B4"
ADDR4=$(python3 - "$B4" <<'PYEOF'
import hashlib, os, sys
root = sys.argv[1]
entries = []
for dirpath, _dirs, files in os.walk(root):
    for f in sorted(files):
        p = os.path.join(dirpath, f)
        rel = os.path.relpath(p, root)
        h = hashlib.sha256(open(p, "rb").read()).hexdigest()
        entries.append((rel, h))
entries.sort()
manifest = "\n".join("%s\0%s" % e for e in entries)
print(hashlib.sha256(manifest.encode()).hexdigest())
PYEOF
)
MARKER4="$WORK/marker4.json"
cat > "$MARKER4" <<JSON
{"target": "$T4", "backup_path": "$B4", "content_address": "$ADDR4"}
JSON
CONFIRM4="$WORK/confirm4.json"
cat > "$CONFIRM4" <<JSON
{"target": "$T4", "operator": "test", "confirmed_at": "2026-09-30T00:00:00Z"}
JSON
( cd "$T4" && exec sleep 30 ) &
LIVE_PID=$!
# wait for the child's cwd to actually resolve under T4 before probing (avoid a race).
for _ in 1 2 3 4 5 6 7 8 9 10; do
  [ "$(readlink -f "/proc/$LIVE_PID/cwd" 2>/dev/null)" = "$(readlink -f "$T4")" ] && break
  sleep 0.2
done
python3 "$TOOL" cleanup --target "$T4" --backup-marker "$MARKER4" --confirmation "$CONFIRM4" \
  --out "$WORK/out4.json" --apply >"$WORK/o4.log" 2>&1
rc=$?
kill "$LIVE_PID" 2>/dev/null; wait "$LIVE_PID" 2>/dev/null
if [ "$rc" -eq 1 ] && [ -f "$T4/marker.txt" ]; then
  ok "hr_bad_live_session_dir: refused (exit 1) while a live pid held the target as cwd"
else
  bad "hr_bad_live_session_dir: expected refused while live, got rc=$rc target-present=$([ -f "$T4/marker.txt" ] && echo yes || echo no)"
fi

# --- hr_good_confirmed_backed_up: everything correct -- executes; backup re-verifies ---
T5="$WORK/t5"; mk_target "$T5" "content-five"
B5="$WORK/backup5"; cp -a "$T5" "$B5"
ADDR5=$(python3 - "$B5" <<'PYEOF'
import hashlib, os, sys
root = sys.argv[1]
entries = []
for dirpath, _dirs, files in os.walk(root):
    for f in sorted(files):
        p = os.path.join(dirpath, f)
        rel = os.path.relpath(p, root)
        h = hashlib.sha256(open(p, "rb").read()).hexdigest()
        entries.append((rel, h))
entries.sort()
manifest = "\n".join("%s\0%s" % e for e in entries)
print(hashlib.sha256(manifest.encode()).hexdigest())
PYEOF
)
MARKER5="$WORK/marker5.json"
cat > "$MARKER5" <<JSON
{"target": "$T5", "backup_path": "$B5", "content_address": "$ADDR5"}
JSON
CONFIRM5="$WORK/confirm5.json"
cat > "$CONFIRM5" <<JSON
{"target": "$T5", "operator": "test", "confirmed_at": "2026-09-30T00:00:00Z"}
JSON
python3 "$TOOL" cleanup --target "$T5" --backup-marker "$MARKER5" --confirmation "$CONFIRM5" \
  --out "$WORK/out5.json" --apply >"$WORK/o5.log" 2>&1
rc=$?
if [ "$rc" -eq 0 ] && [ ! -e "$T5" ] && [ -f "$B5/marker.txt" ] && [ "$(cat "$B5/marker.txt")" = "content-five" ]; then
  ok "hr_good_confirmed_backed_up: executed (exit 0), target removed, backup intact"
else
  bad "hr_good_confirmed_backed_up: expected exit 0 + target removed + backup intact, got rc=$rc target-gone=$([ -e "$T5" ] && echo no || echo yes) backup-ok=$([ -f "$B5/marker.txt" ] && echo yes || echo no)"
fi
if [ -f "$WORK/out5.json" ]; then
  python3 -c "
import json, sys
doc = json.load(open('$WORK/out5.json', encoding='utf-8'))
sys.exit(0 if doc.get('backup_reverified') is True else 1)
" && ok "hr_good_confirmed_backed_up: action.json records backup_reverified: true" \
  || bad "hr_good_confirmed_backed_up: action.json missing backup_reverified: true"
else
  bad "hr_good_confirmed_backed_up: no action.json written"
fi

echo "SUMMARY pass=$PASS fail=$FAIL"
[ "$FAIL" -eq 0 ]
