#!/bin/bash
# Purpose : T179's own remaining gap (SpecKit-004 "fast-dev-cycles", tracked
#           separately as ATM-1109, Task/Medium/Queued) -- RED/regression
#           test for the `triple` subcommand of `plan_struct_check.py`,
#           implementing CT-5 (plan.md's own Constitution-Check table,
#           Post-Design Principle IV): "Every oracle, analyzer, judge and
#           guard ships the self-validation triple". Per plan.md line 128
#           and T179's own tasks.md line: "tasks.md adds the negative
#           controls in T052 (T-C02), T125 (T-B04), T126 (T-B05), T091
#           (T-D06); the box stays unchecked until T179's triple check
#           passes, and T-H08 checks every analyzer task for all three
#           members."
#
# WHERE "analyzer/oracle/judge/guard" SCOPE COMES FROM (not invented,
# constitution 11.4.6 -- see plan_struct_check.py's own top-of-file
# docstring, `triple` section, for the full derivation): common-
# conventions.md's own "### Tool map (contract -> plan file -> plan task)"
# table cross-checked per contract against that SAME contract's own text
# (a contract is in CT-5 scope iff its OWN text genuinely demonstrates all
# three self-validation-triple classes, C-005) -- verified live against the
# real corpus (2026-10-01) to yield exactly the 12 real tool contracts and
# 43 of the 68 real plan tasks, a strict superset of CT-5's own 13 named
# examples (all 13 land inside this 43-task scope).
#
# THIS FILE covers three things: (1) a synthetic, self-contained "mixed"
# fixture set exercising every violation code `compute_triple_violations`
# can emit, including the scope-exclusion negative control (a contract
# missing negative-control in its OWN text must not flag its own task, even
# though that task has zero RED-test coverage at all); (2) a synthetic
# "all-good" fixture set proving a genuinely complete run exits 0 with zero
# violations; (3) a REAL-CORPUS check -- the actual ground truth this task
# exists to confirm -- that T-C02/T-B04/T-B05/T-D06 (the tasks T052/T091/
# T125/T126 added their own negative-control fixture to) are NOT named in
# any violation when `triple` runs against the real plan.md/tasks.md/
# contracts today; and (4) a paired mutation disabling the negative-control
# detection regex, proving the check is genuinely load-bearing rather than a
# rubber stamp (constitution 11.4.201(1)/§1.1).
#
# Producer != Verifier (constitution 11.4.240): this file's own fixture
# documents are plain, self-contained Markdown/shell text -- never
# generated by, nor imported from, `plan_struct_check.py` itself.
set -u

repo_root() { cd "$(dirname "$0")/../../../.." && pwd; }
ROOT=$(repo_root)
FC="$ROOT/constitution/scripts/fastcycle"
TOOL="$FC/verify/plan_struct_check.py"
PLAN_LIVE="$ROOT/specs/004-fast-dev-cycles/plan.md"
TASKS_LIVE="$ROOT/specs/004-fast-dev-cycles/tasks.md"
CONTRACTS_LIVE="$ROOT/specs/004-fast-dev-cycles/contracts"

fail=0
failx() { fail=1; }

TMP=$(mktemp -d) || { echo "NOT ok mktemp failed"; exit 2; }
trap 'rm -rf "$TMP"' EXIT

# --- §11.4.273 control needle: prove the relative-path mechanism itself works ---
KNOWN_PRESENT="$FC/lib/fc_common.py"
if [ ! -f "$KNOWN_PRESENT" ]; then
  echo "NOT ok control needle failed: a KNOWN-PRESENT sibling file"
  echo "     ($KNOWN_PRESENT) does not resolve -- this test's relative-path"
  echo "     computation is broken, so every finding below proves nothing"
  failx
else
  echo "ok control needle: a known-present sibling (lib/fc_common.py) resolves"
  echo "   through this test's own path construction -- the checks below can"
  echo "   be trusted"
fi

# --- (0) the tool + the `triple` subcommand must exist and be registered ---
if [ ! -f "$TOOL" ]; then
  echo "NOT ok verify/plan_struct_check.py is absent -- it was reviewed GO"
  echo "     and committed (T046/T159/T179); a regression removed it"
  failx
  exit $fail
fi
USAGE_OUT=$(python3 "$TOOL" triple --help 2>&1)
if ! printf '%s' "$USAGE_OUT" | grep -q -- "--contracts"; then
  echo "NOT ok 'triple' subcommand is not registered on plan_struct_check.py"
  echo "     (--help output did not mention --contracts): $USAGE_OUT"
  failx
else
  echo "ok 'triple' subcommand is registered (--contracts named in --help)"
fi

# ===========================================================================
# Fixture builder -- writes a self-contained plan.md/tasks.md/contracts/ tree
# under $1 (a directory that must already exist). $2 is the RED-fixture
# shape for needle-tool.md ("full" = golden-good+golden-bad+negative-control
# all present; always used -- needle-legacy.md always ships only two of the
# three, by design, as the permanent scope-exclusion negative control).
# ===========================================================================
build_fixture_tree() {
  dir=$1
  mkdir -p "$dir/contracts" "$dir/fixtures"

  cat >"$dir/plan.md" <<'EOF'
#### T-X01 — needle task, fully compliant triple

- **Removes / measures:** none (needle fixture).
- **Serves:** NEEDLE.
- **Protecting tests:** needle.
- **Rollback:** n/a.
- **Expected saving → measurement:** n/a.

#### T-X02 — needle task, missing its negative-control member

- **Removes / measures:** none (needle fixture).
- **Serves:** NEEDLE.
- **Protecting tests:** needle.
- **Rollback:** n/a.
- **Expected saving → measurement:** n/a.

#### T-Y01 — needle task belonging ONLY to an out-of-scope contract

- **Removes / measures:** none (needle fixture).
- **Serves:** NEEDLE.
- **Protecting tests:** needle.
- **Rollback:** n/a.
- **Expected saving → measurement:** n/a.

#### T-Z01 — needle task whose own contract file is missing

- **Removes / measures:** none (needle fixture).
- **Serves:** NEEDLE.
- **Protecting tests:** needle.
- **Rollback:** n/a.
- **Expected saving → measurement:** n/a.
EOF

  cat >"$dir/tasks.md" <<'EOF'
- [x] N001 [TDD] RED test `fixtures/test_x01_good_red.sh` (golden-good: nominal case; golden-bad: known defect; negative control: a legitimately different but valid input) (plan T-X01; FR-NEEDLE)
- [x] N002 [TDD] RED test `fixtures/test_x02_bad_red.sh` (golden-good: nominal case; golden-bad: known defect) (plan T-X02; FR-NEEDLE)
EOF
  # T-Y01 and T-Z01 deliberately have NO RED-test line at all: T-Y01's own
  # contract is out of scope (so this must never matter); T-Z01's own
  # contract file does not exist (so the per-task test-file check must
  # never even run for it -- the contract_file_missing finding names only
  # the contract, never the task).

  cat >"$dir/contracts/common-conventions.md" <<'EOF'
# Contract: Common Conventions (needle fixture)

### Tool map (contract -> plan file -> plan task)

| Contract | Tool | Plan tasks |
|---|---|---|
| needle-tool | `$FC/needle.py` | T-X01, T-X02 |
| needle-legacy | `$FC/legacy.py` | T-Y01 |
| needle-missing | `$FC/missing.py` | T-Z01 |

Plan tools that no contract covers: none (needle fixture).
EOF

  cat >"$dir/contracts/needle-tool.md" <<'EOF'
# Contract: Needle Tool (fixture)

## RED fixtures

- golden-good: a nominal run.
- golden-bad: a known defect.
- negative-control: a legitimately different but valid input.
EOF

  cat >"$dir/contracts/needle-legacy.md" <<'EOF'
# Contract: Needle Legacy (fixture)

## RED fixtures

- golden-good: a nominal run.
- golden-bad: a known defect.

(This legacy tool's own RED-fixtures list stops at two classes -- needle
fixture, deliberately out of CT-5 scope. NEVER spell out the third class's
own name anywhere in this fixture file, including in this very sentence:
doing so would itself satisfy `_svt_classes_present`'s own detection regex
and defeat the whole point of this fixture -- a real, self-inflicted bug
this file's own author hit and fixed while first authoring this test.)
EOF
  # contracts/needle-missing.md is deliberately NOT created.

  cat >"$dir/fixtures/test_x01_good_red.sh" <<'EOF'
#!/bin/sh
# needle RED test -- golden-good / golden-bad / negative control: control
# needle; golden-bad; negative control -- all three self-validation-triple
# members genuinely present.
echo "golden-good: nominal case"
echo "golden-bad: known defect case"
echo "negative control: legitimately different valid case"
EOF

  cat >"$dir/fixtures/test_x02_bad_red.sh" <<'EOF'
#!/bin/sh
# needle RED test -- stops at two self-validation-triple classes (its own
# third member is deliberately not covered here, and its own NAME is
# deliberately never spelled out anywhere in this file, including in this
# very comment -- doing so would itself satisfy _svt_classes_present's own
# detection regex, the same self-inflicted bug this test's own author hit
# and fixed once already in needle-legacy.md, above).
echo "golden-good: nominal case"
echo "golden-bad: known defect case"
EOF
}

run_triple() {
  # run_triple <dir> <out.json>: invokes the real tool against <dir>'s own
  # fixture tree, rooting RED-test paths at <dir> (tasks.md's own paths are
  # relative, exactly as the real tasks.md's are).
  python3 "$TOOL" triple --plan "$1/plan.md" --tasks "$1/tasks.md" \
    --contracts "$1/contracts" --root "$1" --out "$2"
}

json_get() {
  # json_get <path> <python-expr-over-d>: prints the expression's own value
  # as CANONICAL JSON (sort_keys=True -- never Python repr(), whose dict key
  # order would otherwise depend on insertion order and could mismatch the
  # OUTPUT file's own sorted-key convention, C-002), or "READ-ERROR" if the
  # file cannot be parsed. `eval()` here is safe: the expression is always a
  # literal string THIS test file itself hardcodes at every call site below
  # (never external/operator-supplied input), over `d`, the JSON this SAME
  # test run just wrote to disk -- there is no untrusted-data path into
  # this `eval`.
  python3 -c '
import json, sys
try:
    d = json.load(open(sys.argv[1]))
    print(json.dumps(eval(sys.argv[2]), sort_keys=True))  # noqa: S307 -- see json_get()s own comment above
except Exception as exc:
    print("READ-ERROR: %s" % exc)
' "$1" "$2"
}

echo
echo "=== (1) mixed fixture: exercises every violation code + the scope-"
echo "    exclusion negative control ==="
MIXED="$TMP/mixed"
mkdir -p "$MIXED"
build_fixture_tree "$MIXED"
run_triple "$MIXED" "$MIXED/triple.json" >"$MIXED/stdout.log" 2>"$MIXED/stderr.log"
MIXED_RC=$?
echo "info mixed run: rc=$MIXED_RC"

if [ "$MIXED_RC" -ne 1 ]; then
  echo "NOT ok mixed fixture expected exit 1 (real findings present), got rc=$MIXED_RC"
  echo "     stderr: $(cat "$MIXED/stderr.log")"
  failx
else
  echo "ok mixed fixture real-exits 1 (findings present, as designed)"
fi

IN_SCOPE=$(json_get "$MIXED/triple.json" "sorted(d['in_scope_tasks'])")
if [ "$IN_SCOPE" != '["T-X01", "T-X02"]' ]; then
  echo 'NOT ok mixed fixture in_scope_tasks expected exactly ["T-X01", "T-X02"]'
  echo "     (T-Y01 out-of-scope, T-Z01's contract missing), got: $IN_SCOPE"
  failx
else
  echo 'ok mixed fixture in_scope_tasks == ["T-X01", "T-X02"] -- T-Y01 (out-of-'
  echo "   scope contract) and T-Z01 (missing contract file) correctly excluded"
fi

# --- golden-good member: T-X01's genuinely complete triple must NOT be flagged ---
X01_VIOLATIONS=$(json_get "$MIXED/triple.json" "[v for v in d['violations'] if v.get('task')=='T-X01']")
if [ "$X01_VIOLATIONS" != "[]" ]; then
  echo "NOT ok golden-good: T-X01 (genuinely complete triple) was wrongly"
  echo "     flagged (false positive, constitution 11.4.201(1)): $X01_VIOLATIONS"
  failx
else
  echo "ok golden-good: T-X01's genuinely complete triple (golden-good,"
  echo "   golden-bad, negative-control all present) is correctly NOT flagged"
fi

# --- golden-bad member: T-X02's missing negative-control member must be named ---
X02_VIOLATIONS=$(json_get "$MIXED/triple.json" "[v for v in d['violations'] if v.get('task')=='T-X02']")
EXPECT_X02='[{"code": "triple_incomplete", "files": ["fixtures/test_x02_bad_red.sh"], "missing": ["negative-control"], "task": "T-X02"}]'
if [ "$X02_VIOLATIONS" != "$EXPECT_X02" ]; then
  echo "NOT ok golden-bad: T-X02 (missing its negative-control member) was not"
  echo "     flagged triple_incomplete naming exactly 'negative-control'"
  echo "     expected: $EXPECT_X02"
  echo "     got:      $X02_VIOLATIONS"
  failx
else
  echo "ok golden-bad: T-X02's missing negative-control member is correctly"
  echo "   named as a triple_incomplete finding"
fi

# --- negative control: T-Y01 belongs ONLY to an out-of-scope contract (its
# own text never ships a negative-control fixture) and has ZERO RED-test
# coverage -- yet it must NOT be flagged at all. This is the load-bearing
# false-positive guard: a check that flagged every task with no RED test,
# regardless of whether its contract is even in CT-5 scope, would be a
# bluff-gate (constitution 11.4.201(1)) -- rejecting work this project's
# own real corpus deliberately leaves unscoped (common-conventions.md
# itself, and the real "Plan tools that no contract covers" footnote list,
# both correctly fail the SAME in-scope test for the SAME reason). ---
Y01_VIOLATIONS=$(json_get "$MIXED/triple.json" "[v for v in d['violations'] if v.get('task')=='T-Y01']")
if [ "$Y01_VIOLATIONS" != "[]" ]; then
  echo "NOT ok negative control: T-Y01 (out-of-scope contract, zero RED-test"
  echo "     coverage) was wrongly flagged -- scope exclusion must suppress"
  echo "     this entirely, never report it as if it were in-scope: $Y01_VIOLATIONS"
  failx
else
  echo "ok negative control: T-Y01 (belongs only to needle-legacy, which never"
  echo "   ships its own negative-control fixture) is correctly left unflagged"
  echo "   despite having zero RED-test coverage -- proves the check"
  echo "   genuinely discriminates in-scope from out-of-scope, not a rubber stamp"
fi

# --- contract_file_missing: T-Z01's own contract file was never created ---
MISSING_CONTRACT=$(json_get "$MIXED/triple.json" "[v for v in d['violations'] if v.get('code')=='contract_file_missing']")
if [ "$MISSING_CONTRACT" != '[{"code": "contract_file_missing", "contract": "needle-missing"}]' ]; then
  echo "NOT ok a Tool-map-named contract with no real file (needle-missing)"
  echo "     was not flagged contract_file_missing: $MISSING_CONTRACT"
  failx
else
  echo "ok a Tool-map-named contract with no real .md file is correctly"
  echo "   flagged contract_file_missing, naming the contract"
fi

echo
echo "=== (2) all-good fixture: a genuinely complete scope must real-exit 0 ==="
GOOD="$TMP/good"
mkdir -p "$GOOD/contracts" "$GOOD/fixtures"
cat >"$GOOD/plan.md" <<'EOF'
#### T-X01 — needle task, fully compliant triple

- **Removes / measures:** none (needle fixture).
- **Serves:** NEEDLE.
- **Protecting tests:** needle.
- **Rollback:** n/a.
- **Expected saving → measurement:** n/a.
EOF
cat >"$GOOD/tasks.md" <<'EOF'
- [x] N001 [TDD] RED test `fixtures/test_x01_good_red.sh` (golden-good: nominal case; golden-bad: known defect; negative control: a legitimately different but valid input) (plan T-X01; FR-NEEDLE)
EOF
cat >"$GOOD/contracts/common-conventions.md" <<'EOF'
# Contract: Common Conventions (needle fixture)

### Tool map (contract -> plan file -> plan task)

| Contract | Tool | Plan tasks |
|---|---|---|
| needle-tool | `$FC/needle.py` | T-X01 |

Plan tools that no contract covers: none (needle fixture).
EOF
cat >"$GOOD/contracts/needle-tool.md" <<'EOF'
# Contract: Needle Tool (fixture)

## RED fixtures

- golden-good: a nominal run.
- golden-bad: a known defect.
- negative-control: a legitimately different but valid input.
EOF
cat >"$GOOD/fixtures/test_x01_good_red.sh" <<'EOF'
#!/bin/sh
echo "golden-good: nominal case"
echo "golden-bad: known defect case"
echo "negative control: legitimately different valid case"
EOF

run_triple "$GOOD" "$GOOD/triple.json" >"$GOOD/stdout.log" 2>"$GOOD/stderr.log"
GOOD_RC=$?
if [ "$GOOD_RC" -ne 0 ]; then
  echo "NOT ok all-good fixture expected exit 0, got rc=$GOOD_RC"
  echo "     stderr: $(cat "$GOOD/stderr.log")"
  failx
else
  GOOD_VIOLATIONS=$(json_get "$GOOD/triple.json" "d['violations']")
  if [ "$GOOD_VIOLATIONS" != "[]" ]; then
    echo "NOT ok all-good fixture real-exited 0 but still carries violations: $GOOD_VIOLATIONS"
    failx
  else
    echo "ok all-good fixture (one in-scope task, triple fully present)"
    echo "   real-exits 0 with zero violations"
  fi
fi

echo
echo "=== (3) REAL-CORPUS check -- the ground truth this task exists to"
echo "    confirm: T-C02/T-B04/T-B05/T-D06 (T052/T091/T125/T126's own"
echo "    negative-control additions) must NOT be named in any violation ==="
REAL_OUT="$TMP/real_triple.json"
# --root "$ROOT" is REQUIRED here even though --plan/--tasks/--contracts are
# already absolute ($ROOT-prefixed): tasks.md's OWN "RED test `<path>`"
# lines embed paths relative to the repo root (e.g.
# "constitution/scripts/fastcycle/tests/test_io_trace_red.sh"), and
# `cmd_triple` resolves those EMBEDDED paths relative to CWD when --root is
# omitted -- a real, reproducible bug this test's own author hit while
# first authoring this section: running this file from inside tests/
# (rather than the repo root) silently resolved every RED-test path wrong
# and produced four spurious triple_test_file_unreadable findings for
# T-C02/T-B04/T-B05/T-D06, exactly contradicting section (1)'s own proof
# that --root correctly anchors these same embedded paths.
python3 "$TOOL" triple --plan "$PLAN_LIVE" --tasks "$TASKS_LIVE" \
  --contracts "$CONTRACTS_LIVE" --root "$ROOT" --out "$REAL_OUT" \
  >"$TMP/real_stdout.log" 2>"$TMP/real_stderr.log"
REAL_RC=$?
echo "info real-corpus run: rc=$REAL_RC"
if [ ! -f "$REAL_OUT" ]; then
  echo "NOT ok real-corpus run did not produce an output file at all"
  echo "     (rc=$REAL_RC, stderr: $(cat "$TMP/real_stderr.log")) -- cannot confirm the ground"
  echo "     truth this task exists to check"
  failx
else
  ANY_NAMED=0
  for T in T-C02 T-B04 T-B05 T-D06; do
    NAMED=$(json_get "$REAL_OUT" "[v for v in d['violations'] if v.get('task')=='$T']")
    if [ "$NAMED" != "[]" ]; then
      echo "NOT ok real-corpus run flags $T (its own negative-control fix should"
      echo "     have made it genuinely complete): $NAMED"
      failx
      ANY_NAMED=1
    fi
  done
  if [ "$ANY_NAMED" -eq 0 ]; then
    echo "ok real-corpus run against the LIVE plan.md/tasks.md/contracts confirms"
    echo "   T-C02 (T052), T-B04 (T125), T-B05 (T126) and T-D06 (T091) -- the four"
    echo "   tasks CT-5's own box text named as needing a negative-control fix --"
    echo "   are ALL genuinely complete today, named in zero violations"
  fi
  IN_SCOPE_COUNT=$(json_get "$REAL_OUT" "d['in_scope_task_count']")
  echo "info real-corpus in_scope_task_count=$IN_SCOPE_COUNT (expect 43:"
  echo "     the 12 real tool contracts' own 43 plan tasks, a strict superset"
  echo "     of CT-5's own 13 named examples -- never the full 68-task plan,"
  echo "     never merely the 4 originally-named tasks)"
  if [ "$IN_SCOPE_COUNT" != "43" ]; then
    echo "NOT ok real-corpus in_scope_task_count expected 43, got $IN_SCOPE_COUNT"
    echo "     (a drift in common-conventions.md's own Tool map table, or in"
    echo "     this file's own scope-derivation logic -- investigate before"
    echo "     trusting the finding above)"
    failx
  else
    echo "ok real-corpus in_scope_task_count == 43, matching the mechanical"
    echo "   derivation's own documented, pre-verified real-corpus result"
  fi
  TOTAL_VIOLATIONS=$(json_get "$REAL_OUT" "len(d['violations'])")
  echo "info real-corpus total violations=$TOTAL_VIOLATIONS -- the CT-5"
  echo "   checkbox in plan.md stays UNCHECKED while this is non-zero; every"
  echo "   named task is a REAL, separately-tracked gap (most of the 43"
  echo "   in-scope tools are not yet built -- this is expected, honest, and"
  echo "   is NOT papered over by narrowing scope back to the original 4)"
fi

echo
echo "=== (4) paired mutation: disable negative-control detection and prove"
echo "    it is genuinely load-bearing (constitution 11.4.201(1)/§1.1) ==="
# The mutated copy must live at <mutroot>/verify/plan_struct_check.py with
# <mutroot>/lib resolving to the REAL lib/fc_common.py (the module's own
# `_LIB_DIR = dirname(__file__)/../lib` computation is relative to wherever
# the mutated file itself lives, never the real tree) -- a symlink achieves
# this without copying lib/fc_common.py a second time.
MUTROOT="$TMP/mutroot"
mkdir -p "$MUTROOT/verify"
ln -s "$FC/lib" "$MUTROOT/lib"
MUT_TOOL="$MUTROOT/verify/plan_struct_check.py"
python3 - "$TOOL" "$MUT_TOOL" <<'PY'
import sys
src_path, out_path = sys.argv[1], sys.argv[2]
src = open(src_path, encoding="utf-8").read()
needle = '_SVT_NEG_RE = re.compile(r"negative[-_ ]control|negctrl", re.IGNORECASE)'
if needle not in src:
    print("MUTATION-ANCHOR-NOT-FOUND", file=sys.stderr)
    sys.exit(1)
mutated = src.replace(
    needle, '_SVT_NEG_RE = re.compile(r"ZZZ_NEVER_MATCHES_ANYTHING_ZZZ")')
open(out_path, "w", encoding="utf-8").write(mutated)
PY
MUT_BUILD_RC=$?
if [ "$MUT_BUILD_RC" -ne 0 ] || [ ! -f "$MUT_TOOL" ]; then
  echo "NOT ok could not build the mutated copy (anchor text may have drifted"
  echo "     -- this mutation is no longer a genuine test of the real logic)"
  failx
else
  echo "ok mutated copy built (the real source's own negative-control regex"
  echo "   anchor text was found and genuinely replaced)"
  # The mutation also breaks self_check_triple()'s OWN needle for
  # _svt_classes_present's negctrl recognition -- so the mutated tool is
  # expected to be CAUGHT AT THE SELF-CHECK LAYER (exit 3), never silently
  # produce a false-clean result. This is the established, repeated
  # architecture this file's siblings (self_check_plan/self_check_research)
  # already rely on: a mutation to production logic a self-check needles is
  # caught BEFORE it can ever reach real data, exactly the Producer !=
  # Verifier discipline (constitution 11.4.240) this suite enforces
  # throughout.
  python3 "$MUT_TOOL" triple --plan "$GOOD/plan.md" --tasks "$GOOD/tasks.md" \
    --contracts "$GOOD/contracts" --root "$GOOD" --out "$TMP/mutated_out.json" \
    >"$TMP/mutated_stdout.log" 2>"$TMP/mutated_stderr.log"
  MUT_RC=$?
  if [ "$MUT_RC" -ne 3 ]; then
    echo "NOT ok mutated tool (negative-control detection disabled) was"
    echo "     expected to be caught by its own self-check (exit 3), got"
    echo "     rc=$MUT_RC -- if this is 0, the mutation silently produced a"
    echo "     false-clean result and the check is NOT load-bearing"
    echo "     stdout: $(cat "$TMP/mutated_stdout.log")"
    echo "     stderr: $(cat "$TMP/mutated_stderr.log")"
    failx
  else
    if ! grep -q "self-check FAILED" "$TMP/mutated_stderr.log"; then
      echo "NOT ok mutated tool exited 3 but did not print a 'self-check"
      echo "     FAILED' diagnostic naming the broken check"
      failx
    else
      echo "ok mutated tool (negative-control regex disabled) is caught by its"
      echo "   own self_check_triple() and exits 3, printing a named diagnostic"
      echo "   -- the negative-control detection is genuinely load-bearing,"
      echo "   never a rubber stamp"
    fi
  fi
fi

echo
echo "SUMMARY control_needle=ok mixed_fixture_verified=yes all_good_fixture_verified=yes" \
     "real_corpus_t052_t091_t125_t126_confirmed_complete=yes paired_mutation_caught=yes" \
     "fail=$fail"
exit $fail
